# Generated by Django 4.1.5 on 2023-01-25 17:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('mvts', 'MVTS'), ('functional', 'Functional Network')], max_length=32)),
                ('task', models.CharField(choices=[('supervised', 'Supervised'), ('unsupervised', 'Unsupervised')], max_length=32)),
                ('learning_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=32)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('labels_file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('normalize', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')])),
                ('ml_model', models.CharField(choices=[('rocket', 'ROCKET'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('rnn', 'RNN')], max_length=32)),
                ('hyperparameter', models.CharField(choices=[('hss', 'Hidden State Size'), ('non-linearity', 'Non-linearity')], max_length=32)),
                ('train_split', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(90)])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_datetime', models.DateTimeField(auto_created=True)),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('project_name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('project_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solarflare.projectinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization'), ('school', 'School')], max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('country', models.CharField(choices=[('unitedstates', 'United States'), ('canada', 'Canada')], max_length=32)),
                ('state', models.CharField(max_length=32, null=True)),
                ('access', models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'email')},
                'index_together': {('user', 'email')},
            },
        ),
    ]
