# Generated by Django 4.1.5 on 2023-01-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_datetime',
            field=models.DateTimeField(),
        ),
    ]
