# Generated by Django 4.1.5 on 2023-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0002_alter_project_datetime_alter_project_report_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
