# Generated by Django 4.1.5 on 2023-05-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0004_alter_userinfo_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
