# Generated by Django 4.1.5 on 2023-05-30 18:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0005_alter_project_report_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='hyperparameter',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='activation_func',
            field=models.CharField(choices=[('hss', 'Hidden State Size'), ('non-linearity', 'Non-linearity')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='data_augmentation',
            field=models.CharField(choices=[('pocket', 'Pocket'), ('timegan', 'TimeGan')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='epochs',
            field=models.CharField(choices=[('hss', 'Hidden State Size'), ('non-linearity', 'Non-linearity')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='layers',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='learning_rate',
            field=models.CharField(choices=[('hss', 'Hidden State Size'), ('non-linearity', 'Non-linearity')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='optimization',
            field=models.CharField(choices=[('hss', 'Hidden State Size'), ('non-linearity', 'Non-linearity')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solarflare.projectinfo'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='data_type',
            field=models.CharField(choices=[('mvts', 'MVTS'), ('fn', 'Functional Network')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='learning_type',
            field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='ml_model',
            field=models.CharField(choices=[('rocket', 'ROCKET'), ('lstm', 'LSTM'), ('gru', 'GRU'), ('rnn', 'RNN'), ('sfc', 'Statistical Feature Computation'), ('le', 'Laplacian Eigenmaps'), ('node2vec', 'node2vec'), ('gcn', 'GCN')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='normalize',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='train_split',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
