# Generated by Django 4.1.5 on 2023-05-30 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0007_alter_projectinfo_activation_func_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_info',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='solarflare.project'),
            preserve_default=False,
        ),
    ]
