# Generated by Django 4.1.5 on 2023-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0009_projectresult_remove_projectinfo_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='report',
        ),
    ]
