# Generated by Django 4.1.5 on 2023-06-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0011_alter_userinfo_country_alter_userinfo_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
