# Generated by Django 4.1.5 on 2023-06-06 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solarflare', '0012_remove_userinfo_state_userinfo_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='labels_file',
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=64)),
                ('data_type', models.CharField(choices=[('mvts', 'MVTS'), ('fn', 'Functional Network')], max_length=32)),
                ('train_data', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('label_data', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('train_volume', models.CharField(blank=True, max_length=64, null=True)),
                ('label_volume', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='data_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solarflare.dataset'),
        ),
    ]
