# Generated by Django 4.1.5 on 2023-06-06 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0013_remove_projectinfo_data_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.dataset'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solarflare.projectinfo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solarflare.projectresult'),
        ),
    ]
