# Generated by Django 4.1.5 on 2023-06-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarflare', '0014_alter_project_data_info_alter_project_project_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='data_augmentation',
            field=models.CharField(blank=True, choices=[('smote', 'SMOTE'), ('timegan', 'TimeGan')], max_length=32, null=True),
        ),
    ]
