# Generated by Django 4.1.5 on 2023-06-21 19:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solarflare', '0017_dataset_description_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, upload_to='bugreport/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('update', 'Update'), ('issue', 'Issue')], max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('urgent', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='data_augmentation',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='normalize',
        ),
        migrations.AddField(
            model_name='dataset',
            name='preprocessing',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(blank=True, choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='layers',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='FNDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('report_datetime', models.DateTimeField(auto_now=True)),
                ('data', models.ManyToManyField(to='solarflare.file')),
                ('mvts_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('ui', 'User Interface'), ('server', 'Server'), ('security', 'Security'), ('programing', 'Programing')], max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('urgent', models.IntegerField(blank=True, choices=[(1, 'Yes'), (0, 'No')], null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.bugfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AugmentedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_augmentation', models.CharField(blank=True, choices=[('smote', 'SMOTE'), ('timegan', 'TimeGan')], max_length=32, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('report_datetime', models.DateTimeField(auto_now=True)),
                ('data', models.ManyToManyField(to='solarflare.file')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='data_aug_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.augmenteddataset'),
        ),
        migrations.AddField(
            model_name='project',
            name='fn_data_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='solarflare.fndataset'),
        ),
    ]
